name: Deploy .NET isolated Azure Function App

# This file is what is going to tell GitHub actions to create our CI/CD pipeline.
# When we do a certain action, the pipeline is ran.

# This grabs our API (which is meant to host our JSON information) and deploy it to our Azure function.

# On workflow_dispatchwe will have a manual way to run the workflow.
# And whenever we make a push to the main branch.

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_NAME: 'serverlessresumeapi'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '6.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/src'
          dotnet build --configuration Release --output ./output
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/src/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}